# Configura��es do Pisk & Click - Gerado automaticamente

# Detec��o de piscadas
EAR_THRESHOLD = 0.351
BLINK_CONSECUTIVE_FRAMES = 5

# Mouse
SMOOTHING_FACTOR = 0.5
MOUSE_SENSITIVITY_MULTIPLIER = 0.8
MOUSE_ACCELERATION = 0.7

# �rea de controle
CONTROL_AREA_X_MIN = 0.25
CONTROL_AREA_X_MAX = 0.75
CONTROL_AREA_Y_MIN = 0.25
CONTROL_AREA_Y_MAX = 0.75

# Cliques
CLICK_DEBOUNCE_TIME = 0.6
DOUBLE_BLINK_PROTECTION = True

# Performance
PROCESS_EVERY_N_FRAMES = 1

# Constantes fixas
NOSE_TIP_INDEX = 1
# Landmarks invertidos por causa do flip da imagem (cv2.flip)
LEFT_EYE_LANDMARKS_IDXS = [33, 160, 158, 133, 153, 144]  # Era RIGHT
RIGHT_EYE_LANDMARKS_IDXS = [362, 385, 387, 263, 373, 380]  # Era LEFT
REFINE_LANDMARKS = True
INVERT_X_AXIS = False
INVERT_Y_AXIS = False
MIN_MOVEMENT_THRESHOLD = 2
SENSITIVITY_ADJUSTMENT_STEP = 0.1
MIN_SENSITIVITY = 0.5
MAX_SENSITIVITY = 2.5
DOUBLE_BLINK_THRESHOLD = 0.05
DOUBLE_BLINK_COOLDOWN = 1.0
